name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: 1.56.0

      - name: Build for Linux
        run: |
          ./build-static-bins.sh
        working-directory: ./src

      - name: Build for Windows
        run: |
          cargo build --release --target x86_64-pc-windows-gnu
        working-directory: ./src

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-binary
          path: ./src/target/release/udp2tcp

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-binary
          path: ./src/target/x86_64-pc-windows-gnu/release/udp2tcp.exe
