name: Build udp-over-tcp binaries

on:
  push:
    tags:
      - 'v*'   # 只有打 tag 时触发构建（比如 v1.0.0）
  workflow_dispatch:   # 手动触发

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        target: [x86_64-unknown-linux-gnu, x86_64-pc-windows-gnu]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: udp-over-tcp-${{ matrix.os }}-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/*
